### ISSUE TITLE
Which version of the specification is this server implementing?

### ISSUE THREAD

**Issue by mariorguezari** [AriHealth/hapi-fhir-jpaserver-oauth#26]
Probably it should be included in the README.md
Is this supporting R4? DSTU3? 
How can we check (prior to launching the project?)

**Comment by carloscaverobarca** [comment]
For the moment it supports DST3. The official HAPI starter project allows to configure the version. Can you update the README with this information and open a new issue to upgrade to HAPI starter project? Or we can go for Spring Framework

**Comment by mariorguezari** [comment]
Thanks. Readme updated.
