### ISSUE TITLE
problem after OAUTH_ENABLE=true

### ISSUE THREAD

**Issue by bishaladhikari** [AriHealth/hapi-fhir-jpaserver-oauth#29]
After oauth_enable set to true I tried building the app with docker-compose. Even if I use the correct token and endpoint there is 404 null error.

Step to reproduce:
1: set OAUTH_ENABLE=true in .env  and remove comment (OAUTH_ENABLE and OAUTH_URL) from docker-compose.yml
2: docker-compose up -d.
3: create realm, client and user as stated on  README.
4: fetch token from POST http://localhost:8081/login 
5: use token with header Authorization Bearer token. I tried it in postman with  endpoint
GET http://localhost:8080/baseDstu3/Patient

 The error response is as follows.
{
    "resourceType": "OperationOutcome",
    "text": {
        "status": "generated",
        "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">ERROR</td><td>[]</td><td><pre>404 null</pre></td>\n\t\t\t\t\t\n\t\t\t\t\n\t\t\t</tr>\n\t\t</table>\n\t</div>"
    },
    "issue": [
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "404 null"
        }
    ]
}

Thanks in advance. Please help me if I am missing any steps or configuration.

**Comment by carloscaverobarca** [comment]
Hi @bishaladhikari first of all, thanks for using the component and improve it with issues. AFAIK you are doing things right. Let me check what is happening. A short question, I am assuming that HAPI is working without OAUTH enabled, right? 404 is about a resource missed. In any case, I realized that the docker-compose used a wrong keycloak-auth module so I will push new changes shortly and let you know. Regards, Carlos.

**Comment by bishaladhikari** [comment]
Yes, it is working without Oauth enabled.

**Comment by bishaladhikari** [comment]
@carloscaverobarca How long will it take for the fixes? Can you suggest me any rough workarounds for the problem for the time being? :)

**Comment by carloscaverobarca** [comment]
@bishaladhikari, first of all, thanks for pointing this out, could you give a try? We also realized that there is an unexpected behaviour when the token is not valid or expired. A 500 internal server error is raised instead of 401, we are working on that but for this the oauth-easy image needs to catch the exception properly. We are also planning to upgrade to 4.1.0. Stay tune. I will close the issue once you confirm it is working, I tested with Postman and I received the patient bundle.

**Comment by bishaladhikari** [comment]
@carloscaverobarca  Many thanks for the quick response. It is now working. Really appreciate the work, thank you.

**Comment by carloscaverobarca** [comment]
@bishaladhikari glad to hear that. Again thanks for pointing the issue. I will close it then.
