### ISSUE TITLE
feature: refactor packages to avoid "demo"

### ISSUE THREAD

**Issue by mariorguezari** [AriHealth/hapi-fhir-jpaserver-oauth#7]
# Feature Request

**Describe the Feature Request**

In case the project continues, the packages notation ca.uhn.fhir.jpa.demo doesn't seem very precise containing a "demo" level.

**Is your feature request related to a problem? Please describe**

No.

**Describe Preferred Solution**

net.atos.ari.health.cdr or net.atos.ari.cdr for example.

**Comment by carloscaverobarca** [comment]
In summary:
- I would use the coordinates net.atos.ari.health.cdr.jpa.starter
- I would remove any reference to DSTU2 and only keep DSTU3
- R4 would be cover with a fork from the [official starter](https://github.com/hapifhir/hapi-fhir-jpaserver-starter) to cover the updates through rebases
@santiago-aso

**Comment by mariorguezari** [comment]
I agree. Just a question: what about skipping the "jpa" level -> will we have some time something different than JPA? 

I think as soon as the R4 is ready, this repository will be obsolete. In any case, it seems worthy to update to DSTU3 if it doesn't take too much effort.

**Comment by carloscaverobarca** [comment]
Totally agree, "jpa" level removed. And what about ElasticSearch should we keep it? I guess it can also be deleted.

**Comment by mariorguezari** [comment]
I never used myself the ElasticSearch  the example server integrating the ElasticSearch engine, don't know what to answer to your question.. Is it production ready? In that case it is ok to keep it, I guess; otherwise it is probably noise in the repository.
