### ISSUE TITLE
Use of mysql

### ISSUE THREAD

**Issue by mariorguezari** [AriHealth/hapi-fhir-jpaserver-oauth#8]
Check compatibility of the mysql dependency and the licenses.

**Comment by carloscaverobarca** [comment]
I open two new issues to cover DB connectors (MariaDB and PostgreSQL) compliant with Apache 2.0.

**Comment by carloscaverobarca** [comment]
In any case we need to gather the third party licenses and carefully check the repo. Close the issue.
